services:
  postgres:
    image: postgres:15.1
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '${REDIS_PORT}:6379'

  # main:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   command: npm run dev
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     - postgres
