version: '3.9'

networks:
  backend-net:
    external: true

services:
  main:
    build:
      context: .
    container_name: backend
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000' # change to your desired port
    command: npm run dev
    environment:
      DATABASE_URL: 'postgresql://user:pass@postgres:5432/db'
      REDIS_URL: 'redis://redis:6379'
    networks:
      - backend-net
